### PR TITLE
increase button size, font size, and icon size

### LINKED ISSUE #214: Increase default menu button size
## Request to increase the height on the default menu buttons.
Signs and Markings technicians would regularly use these buttons and on a tablet, these would be great if they were larger buttons to click on.

### [Signs - My Work Orders](https://atd.knack.com/signs-markings#my-work-orders/)
`scene: 1085`

image

### [Signs - Work Order Details](https://atd.knack.com/signs-markings#my-work-orders/view-work-orders-details-sign/5d39f42940c00f24eaf9e05a/)
`scene: https://builder.knack.com/atd/signs-markings#pages/scene_1028/views/view_2684`

image

### [Markings - Jobs](https://atd.knack.com/signs-markings#jobs/)
`scene: 717`

image

### [Markings - Job Details](https://atd.knack.com/signs-markings#jobs/view-work-orders-markings-job-details/5d3a285cafee63251a093a1d/)
`scene: 716`

image

`scene: 894`
image

### PR DESCRIPTION
**Pull request by mateoclarke**
Closes #214

### CODE REVIEW

**Comment by dianamartin** [comment]
- [x] Reviewed `Job Details` page, had to rename some buttons so they would fit better on tablet.
- [x] Reviewed `Jobs` page
- [x] Reviewed `My Work Orders | Assigned` page
- [x] Reviewed `Signs Work Order Details` page
- [x] Reviewed `Signs Work Order>Location Details` page
>Saw that the `Photo` button was the only one not enlarged

**Comment by mateoclarke** [comment]
@dianamartin, just dropped the `WIP` label. The code in this PR is in the test environment. If it all looks good to you I can merge.

**Comment by dianamartin** [comment]
@mateoclarke I sent this to the Signs and Markings team to review and I was waiting on feedback from them before we merge. Maybe I'll reach out by the end of the day so we can get a confirmation from them.

**Comment by mateoclarke** [comment]
I'm going to go ahead and merge this since you've reviewed @dianamartin. If SMB has feedback, we can open another issue.

**Pull request merged**
