### PR TITLE
js-calc

### PR DESCRIPTION
**Pull request by tillyw**

### CODE REVIEW

**Review by mateoclarke — APPROVED** [review]
👍

**Comment by mateoclarke** [comment]
To answer your question @tcwcodes, its not urgent. The deploy preview link is fine to keep in prod until your back with us on 9/10

**Comment by amenity** [comment]
@tcwcodes — is this connected to an issue?

**Comment by mateoclarke** [comment]
@amenity it was originally connected to this one: https://github.com/cityofaustin/atd-data-tech/issues/80

This PR just moves the calculator from being hosted on transportation.austintexas.io to being hosted with the relevant Knack app. Maybe this is the issue we made for that step? https://github.com/cityofaustin/atd-knack-signs-markings/issues/161

**Pull request closed without merging**
